openapi: 3.0.1
info:
  title: Weather API
  version: "1.0"
  description: A simple Weather API for demonstration purposes
servers:
  - url: https://api.weather.example.com/v1
    description: Production server
paths:
  /weather:
    get:
      summary: Get current weather
      description: Returns current weather information for a specified location
      operationId: getCurrentWeather
      parameters:
        - name: city
          in: query
          description: City name to get weather for
          required: true
          schema:
            type: string
            example: "London"
        - name: units
          in: query
          description: Units of measurement (metric or imperial)
          required: false
          schema:
            type: string
            enum:
              - metric
              - imperial
            default: metric
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherResponse'
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: City not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /weather/forecast:
    get:
      summary: Get weather forecast
      description: Returns weather forecast for the next 5 days
      operationId: getWeatherForecast
      parameters:
        - name: city
          in: query
          description: City name to get forecast for
          required: true
          schema:
            type: string
            example: "Paris"
        - name: days
          in: query
          description: Number of days for forecast (1-5)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 5
            default: 5
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastResponse'
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    WeatherResponse:
      type: object
      properties:
        city:
          type: string
          description: City name
          example: "London"
        temperature:
          type: number
          description: Current temperature
          example: 15.5
        humidity:
          type: integer
          description: Humidity percentage
          example: 65
        conditions:
          type: string
          description: Weather conditions
          example: "Partly cloudy"
        wind_speed:
          type: number
          description: Wind speed
          example: 12.5
        timestamp:
          type: string
          format: date-time
          description: Time of weather data
    ForecastResponse:
      type: object
      properties:
        city:
          type: string
          description: City name
        forecast:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              temperature_high:
                type: number
              temperature_low:
                type: number
              conditions:
                type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          description: Error code
        message:
          type: string
          description: Error message

# Made with Bob
